open orders state reset when wallet switch
mithraiclabs/psyoptions-frontend pull request #793
Opened 2022-02-01 13:38 UTC by haroonpsyoptions

2022-02-01 16:15 UTC, Taylor123 commented on src/components/WalletStatus.tsx
> +      const options = (await program?.account.optionMarket.all()) as
we should strive to contain the inserting/reseting of options to the `useLoadOptionMarkets`, so we can ensure it's performant. This can be an expensive operation

2022-02-01 16:17 UTC, Taylor123 commented on src/recoil/options/atoms.ts
> +          _optionIds.forEach((_optionId) =>
nice, this is a great way to handle the reset!

2022-02-01 16:19 UTC, Taylor123 commented on src/components/WalletStatus.tsx
> +} from '@/recoil';
let's use relative imports if that's ok. It doesn't look like we have this alias set up.

If it's a default for craco, let me know!

2022-02-01 16:21 UTC, Taylor123 requested changes
Had some questions/comments about using existing hooks

2022-02-01 19:13 UTC, haroonpsyoptions commented on src/components/WalletStatus.tsx
> +    if (program && dexProgramId && _quoteMint) {
Taylor, I had tried to use useLoadOptionOpenOrders which already created but that contains react hooks and recoil init which is not allowed in functional body but in a component. I tried to make up gradations on these (useLoadOptionOpenOrders, useLoadOptionMarkets) files but I cannot remove recoil from that.

2022-02-01 19:22 UTC, Taylor123 commented on src/components/WalletStatus.tsx
> +    if (program && dexProgramId && _quoteMint) {
What were the errors that prevented Recoil from being used? Recoil looks to be used in these current changes fine.

2022-02-02 16:36 UTC, Taylor123 approved these changes
looks great!

2022-02-03 13:43 UTC, merged